stages:
  - test

maven:
  stage: test
  image: maven:latest
  variables:
    MAVEN_OPTS: >-
      -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  cache:
    paths:
      - .m2/repository
  script:
    - mvn --version
#    - mvn test
    - echo $NVD_API_KEY
    - echo $CI_PROJECT_DIR
    - mvn -DnvdApiKey=$NVD_API_KEY verify # runs OWASP dependency-check
#   - mvn verify # runs OWASP dependency-check
  artifacts:
    paths:
      - target/dependency-check-report.html

#trivy:
#  stage: test
#  image: curlimages/curl:latest
#  script:
 #   - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b .
 #   - ./trivy fs .

# included in test stage
#include:
 # - template: Jobs/SAST.gitlab-ci.yml
