name: GitHub Actions
on: [push]
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Java and Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Show Java and Maven versions
        shell: bash
        run: |
          java --version
          mvn --version
      - name: Run unit tests
        shell: bash
        run: |
          mvn test
      - name: Run OWASP dependency-check
        shell: bash
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mvn -DnvdApiKey=$NVD_API_KEY -DnvdValidForHours=0 -DnvdApiDelay=5000 org.owasp:dependency-check-maven:check
      - name: Archive dependency check results
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check
          path: target/dependency-check-report.html
