name: GitHub Actions
on: [push]
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
      - run: java --version
      - run: mvn --version
      - run: mvn test
