name: GitHub Actions
on: [push]
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: mvn --version
      - run: mvn test
